// trucks.js
// Replace with your real API call when backend is ready.
// Keep the same object shape so TruckCard works without changes.

const trucks = [
  {
    id: 1,
    name: "Smoky Joe's BBQ",
    cuisine: 'BBQ',
    category: 'Burgers',
    rating: 4.8,
    reviewCount: 342,
    priceRange: '$$',
    isOpen: true,
    distance: '0.3 mi',
    hours: '11:00AM - 9:00PM',
    location: 'Downtown Food Park',
    description: 'Authentic smoked meats with homemade sauces. Our brisket has won 3 local awards.',
    image: 'https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=400&q=80',
  },
  {
    id: 2,
    name: 'Taco Libre',
    cuisine: 'Mexican',
    category: 'Mexican',
    rating: 4.6,
    reviewCount: 218,
    priceRange: '$',
    isOpen: true,
    distance: '0.5 mi',
    hours: '10:00AM - 10:00PM',
    location: 'Westside Plaza',
    description: 'Traditional street tacos with fresh, handmade tortillas and spicy salsas.',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&q=80',
  },
  {
    id: 3,
    name: 'Rolling Sushi',
    cuisine: 'Japanese',
    category: 'Fast Food',
    rating: 4.9,
    reviewCount: 156,
    priceRange: '$$$',
    isOpen: true,
    distance: '0.8 mi',
    hours: '11:30AM - 8:30PM',
    location: 'University Avenue',
    description: 'Premium sushi rolls and bento boxes made with fresh, locally sourced fish.',
    image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=400&q=80',
  },
  {
    id: 4,
    name: 'The Crepe Cart',
    cuisine: 'French',
    category: 'Desserts',
    rating: 4.7,
    reviewCount: 189,
    priceRange: '$$',
    isOpen: false,
    distance: '1.2 mi',
    hours: '8:00AM - 6:00PM',
    location: 'Farmers Market',
    description: 'Sweet and savory French crepes made to order. Try our signature Nutella crepe.',
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400&q=80',
  },
  {
    id: 5,
    name: 'Burger Bus',
    cuisine: 'American',
    category: 'Burgers',
    rating: 4.5,
    reviewCount: 421,
    priceRange: '$$',
    isOpen: true,
    distance: '0.6 mi',
    hours: '11:00AM - 11:00PM',
    location: 'East Side Station',
    description: 'Classic American burgers with a modern twist. Our double cheeseburger is a local favorite.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80',
  },
  {
    id: 6,
    name: 'Green Machine',
    cuisine: 'Healthy',
    category: 'Drinks',
    rating: 4.4,
    reviewCount: 97,
    priceRange: '$$',
    isOpen: true,
    distance: '1.0 mi',
    hours: '7:00AM - 5:00PM',
    location: 'Tech Park Courtyard',
    description: 'Cold-pressed juices, smoothies, and healthy bowls for a refreshing meal.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
  },
];

export default trucks;
